// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dizen/common/v1/access.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a piece of content is accessed. Values carry the enum prefix because in protobuf
// enum values share the namespace of the package that contains them.
type AccessType int32

const (
	AccessType_ACCESS_TYPE_UNSPECIFIED  AccessType = 0
	AccessType_ACCESS_TYPE_FREE         AccessType = 1
	AccessType_ACCESS_TYPE_PREMIUM      AccessType = 2
	AccessType_ACCESS_TYPE_SUBSCRIPTION AccessType = 3
)

// Enum value maps for AccessType.
var (
	AccessType_name = map[int32]string{
		0: "ACCESS_TYPE_UNSPECIFIED",
		1: "ACCESS_TYPE_FREE",
		2: "ACCESS_TYPE_PREMIUM",
		3: "ACCESS_TYPE_SUBSCRIPTION",
	}
	AccessType_value = map[string]int32{
		"ACCESS_TYPE_UNSPECIFIED":  0,
		"ACCESS_TYPE_FREE":         1,
		"ACCESS_TYPE_PREMIUM":      2,
		"ACCESS_TYPE_SUBSCRIPTION": 3,
	}
)

func (x AccessType) Enum() *AccessType {
	p := new(AccessType)
	*p = x
	return p
}

func (x AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_dizen_common_v1_access_proto_enumTypes[0].Descriptor()
}

func (AccessType) Type() protoreflect.EnumType {
	return &file_dizen_common_v1_access_proto_enumTypes[0]
}

func (x AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessType.Descriptor instead.
func (AccessType) EnumDescriptor() ([]byte, []int) {
	return file_dizen_common_v1_access_proto_rawDescGZIP(), []int{0}
}

var File_dizen_common_v1_access_proto protoreflect.FileDescriptor

const file_dizen_common_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x1cdizen/common/v1/access.proto\x12\x0fdizen.common.v1*v\n" +
	"\n" +
	"AccessType\x12\x1b\n" +
	"\x17ACCESS_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACCESS_TYPE_FREE\x10\x01\x12\x17\n" +
	"\x13ACCESS_TYPE_PREMIUM\x10\x02\x12\x1c\n" +
	"\x18ACCESS_TYPE_SUBSCRIPTION\x10\x03B\xcd\x01\n" +
	"\x13com.dizen.common.v1B\vAccessProtoP\x01ZKgithub.com/nicodanke/dizen-v2-backend/pkg/genproto/dizen/common/v1;commonv1\xa2\x02\x03DCX\xaa\x02\x0fDizen.Common.V1\xca\x02\x0fDizen\\Common\\V1\xe2\x02\x1bDizen\\Common\\V1\\GPBMetadata\xea\x02\x11Dizen::Common::V1b\x06proto3"

var (
	file_dizen_common_v1_access_proto_rawDescOnce sync.Once
	file_dizen_common_v1_access_proto_rawDescData []byte
)

func file_dizen_common_v1_access_proto_rawDescGZIP() []byte {
	file_dizen_common_v1_access_proto_rawDescOnce.Do(func() {
		file_dizen_common_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dizen_common_v1_access_proto_rawDesc), len(file_dizen_common_v1_access_proto_rawDesc)))
	})
	return file_dizen_common_v1_access_proto_rawDescData
}

var file_dizen_common_v1_access_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dizen_common_v1_access_proto_goTypes = []any{
	(AccessType)(0), // 0: dizen.common.v1.AccessType
}
var file_dizen_common_v1_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dizen_common_v1_access_proto_init() }
func file_dizen_common_v1_access_proto_init() {
	if File_dizen_common_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dizen_common_v1_access_proto_rawDesc), len(file_dizen_common_v1_access_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dizen_common_v1_access_proto_goTypes,
		DependencyIndexes: file_dizen_common_v1_access_proto_depIdxs,
		EnumInfos:         file_dizen_common_v1_access_proto_enumTypes,
	}.Build()
	File_dizen_common_v1_access_proto = out.File
	file_dizen_common_v1_access_proto_goTypes = nil
	file_dizen_common_v1_access_proto_depIdxs = nil
}
