// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dizen/common/v1/device.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Platform of the device originating the call.
type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_IOS         Platform = 1
	Platform_PLATFORM_ANDROID     Platform = 2
	Platform_PLATFORM_WEB         Platform = 3
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_IOS",
		2: "PLATFORM_ANDROID",
		3: "PLATFORM_WEB",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_IOS":         1,
		"PLATFORM_ANDROID":     2,
		"PLATFORM_WEB":         3,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_dizen_common_v1_device_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_dizen_common_v1_device_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_dizen_common_v1_device_proto_rawDescGZIP(), []int{0}
}

// Device identification. It accompanies session creation and stays attached to the
// session so it can be revoked individually (02 section 1, sessions table).
type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier generated by the app, unique per installation.
	DeviceId string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform Platform `protobuf:"varint,2,opt,name=platform,proto3,enum=dizen.common.v1.Platform" json:"platform,omitempty"`
	// Hardware model, as reported by the operating system.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// App version, in semver format.
	AppVersion string `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// Operating system version.
	OsVersion     string `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_dizen_common_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_common_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_dizen_common_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

var File_dizen_common_v1_device_proto protoreflect.FileDescriptor

const file_dizen_common_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x1cdizen/common/v1/device.proto\x12\x0fdizen.common.v1\x1a\x1bbuf/validate/validate.proto\"\xde\x01\n" +
	"\n" +
	"DeviceInfo\x12'\n" +
	"\tdevice_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\bdeviceId\x125\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x19.dizen.common.v1.PlatformR\bplatform\x12\x1e\n" +
	"\x05model\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x05model\x12(\n" +
	"\vapp_version\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18 R\n" +
	"appVersion\x12&\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18 R\tosVersion*^\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x01\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x02\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x03B\xcd\x01\n" +
	"\x13com.dizen.common.v1B\vDeviceProtoP\x01ZKgithub.com/nicodanke/dizen-v2-backend/pkg/genproto/dizen/common/v1;commonv1\xa2\x02\x03DCX\xaa\x02\x0fDizen.Common.V1\xca\x02\x0fDizen\\Common\\V1\xe2\x02\x1bDizen\\Common\\V1\\GPBMetadata\xea\x02\x11Dizen::Common::V1b\x06proto3"

var (
	file_dizen_common_v1_device_proto_rawDescOnce sync.Once
	file_dizen_common_v1_device_proto_rawDescData []byte
)

func file_dizen_common_v1_device_proto_rawDescGZIP() []byte {
	file_dizen_common_v1_device_proto_rawDescOnce.Do(func() {
		file_dizen_common_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dizen_common_v1_device_proto_rawDesc), len(file_dizen_common_v1_device_proto_rawDesc)))
	})
	return file_dizen_common_v1_device_proto_rawDescData
}

var file_dizen_common_v1_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dizen_common_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dizen_common_v1_device_proto_goTypes = []any{
	(Platform)(0),      // 0: dizen.common.v1.Platform
	(*DeviceInfo)(nil), // 1: dizen.common.v1.DeviceInfo
}
var file_dizen_common_v1_device_proto_depIdxs = []int32{
	0, // 0: dizen.common.v1.DeviceInfo.platform:type_name -> dizen.common.v1.Platform
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dizen_common_v1_device_proto_init() }
func file_dizen_common_v1_device_proto_init() {
	if File_dizen_common_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dizen_common_v1_device_proto_rawDesc), len(file_dizen_common_v1_device_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dizen_common_v1_device_proto_goTypes,
		DependencyIndexes: file_dizen_common_v1_device_proto_depIdxs,
		EnumInfos:         file_dizen_common_v1_device_proto_enumTypes,
		MessageInfos:      file_dizen_common_v1_device_proto_msgTypes,
	}.Build()
	File_dizen_common_v1_device_proto = out.File
	file_dizen_common_v1_device_proto_goTypes = nil
	file_dizen_common_v1_device_proto_depIdxs = nil
}
