// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dizen/common/v1/geo.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Geographic point in WGS-84 (EPSG:4326), the same reference system PostGIS uses in
// tours_db.
type GeoPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude in decimal degrees.
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	// Longitude in decimal degrees.
	Lng           float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_dizen_common_v1_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_common_v1_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_dizen_common_v1_geo_proto_rawDescGZIP(), []int{0}
}

func (x *GeoPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoPoint) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_dizen_common_v1_geo_proto protoreflect.FileDescriptor

const file_dizen_common_v1_geo_proto_rawDesc = "" +
	"\n" +
	"\x19dizen/common/v1/geo.proto\x12\x0fdizen.common.v1\x1a\x1bbuf/validate/validate.proto\"`\n" +
	"\bGeoPoint\x12)\n" +
	"\x03lat\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x03lat\x12)\n" +
	"\x03lng\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x03lngB\xca\x01\n" +
	"\x13com.dizen.common.v1B\bGeoProtoP\x01ZKgithub.com/nicodanke/dizen-v2-backend/pkg/genproto/dizen/common/v1;commonv1\xa2\x02\x03DCX\xaa\x02\x0fDizen.Common.V1\xca\x02\x0fDizen\\Common\\V1\xe2\x02\x1bDizen\\Common\\V1\\GPBMetadata\xea\x02\x11Dizen::Common::V1b\x06proto3"

var (
	file_dizen_common_v1_geo_proto_rawDescOnce sync.Once
	file_dizen_common_v1_geo_proto_rawDescData []byte
)

func file_dizen_common_v1_geo_proto_rawDescGZIP() []byte {
	file_dizen_common_v1_geo_proto_rawDescOnce.Do(func() {
		file_dizen_common_v1_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dizen_common_v1_geo_proto_rawDesc), len(file_dizen_common_v1_geo_proto_rawDesc)))
	})
	return file_dizen_common_v1_geo_proto_rawDescData
}

var file_dizen_common_v1_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dizen_common_v1_geo_proto_goTypes = []any{
	(*GeoPoint)(nil), // 0: dizen.common.v1.GeoPoint
}
var file_dizen_common_v1_geo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dizen_common_v1_geo_proto_init() }
func file_dizen_common_v1_geo_proto_init() {
	if File_dizen_common_v1_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dizen_common_v1_geo_proto_rawDesc), len(file_dizen_common_v1_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dizen_common_v1_geo_proto_goTypes,
		DependencyIndexes: file_dizen_common_v1_geo_proto_depIdxs,
		MessageInfos:      file_dizen_common_v1_geo_proto_msgTypes,
	}.Build()
	File_dizen_common_v1_geo_proto = out.File
	file_dizen_common_v1_geo_proto_goTypes = nil
	file_dizen_common_v1_geo_proto_depIdxs = nil
}
