// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dizen/common/v1/media.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reference to an image stored outside the database, in the S3-compatible bucket
// (ADR A-5). The URL is signed and short-lived; the bucket is never public.
type MediaRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Signed URL. It must not be cached beyond its expiry.
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Width  int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// Low-resolution placeholder to paint while the image loads.
	Blurhash string `protobuf:"bytes,5,opt,name=blurhash,proto3" json:"blurhash,omitempty"`
	// Alternative text for accessibility.
	AltText       string `protobuf:"bytes,6,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRef) Reset() {
	*x = MediaRef{}
	mi := &file_dizen_common_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRef) ProtoMessage() {}

func (x *MediaRef) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_common_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRef.ProtoReflect.Descriptor instead.
func (*MediaRef) Descriptor() ([]byte, []int) {
	return file_dizen_common_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaRef) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaRef) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaRef) GetBlurhash() string {
	if x != nil {
		return x.Blurhash
	}
	return ""
}

func (x *MediaRef) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

var File_dizen_common_v1_media_proto protoreflect.FileDescriptor

const file_dizen_common_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x1bdizen/common/v1/media.proto\x12\x0fdizen.common.v1\"\x91\x01\n" +
	"\bMediaRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1a\n" +
	"\bblurhash\x18\x05 \x01(\tR\bblurhash\x12\x19\n" +
	"\balt_text\x18\x06 \x01(\tR\aaltTextB\xcc\x01\n" +
	"\x13com.dizen.common.v1B\n" +
	"MediaProtoP\x01ZKgithub.com/nicodanke/dizen-v2-backend/pkg/genproto/dizen/common/v1;commonv1\xa2\x02\x03DCX\xaa\x02\x0fDizen.Common.V1\xca\x02\x0fDizen\\Common\\V1\xe2\x02\x1bDizen\\Common\\V1\\GPBMetadata\xea\x02\x11Dizen::Common::V1b\x06proto3"

var (
	file_dizen_common_v1_media_proto_rawDescOnce sync.Once
	file_dizen_common_v1_media_proto_rawDescData []byte
)

func file_dizen_common_v1_media_proto_rawDescGZIP() []byte {
	file_dizen_common_v1_media_proto_rawDescOnce.Do(func() {
		file_dizen_common_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dizen_common_v1_media_proto_rawDesc), len(file_dizen_common_v1_media_proto_rawDesc)))
	})
	return file_dizen_common_v1_media_proto_rawDescData
}

var file_dizen_common_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dizen_common_v1_media_proto_goTypes = []any{
	(*MediaRef)(nil), // 0: dizen.common.v1.MediaRef
}
var file_dizen_common_v1_media_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dizen_common_v1_media_proto_init() }
func file_dizen_common_v1_media_proto_init() {
	if File_dizen_common_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dizen_common_v1_media_proto_rawDesc), len(file_dizen_common_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dizen_common_v1_media_proto_goTypes,
		DependencyIndexes: file_dizen_common_v1_media_proto_depIdxs,
		MessageInfos:      file_dizen_common_v1_media_proto_msgTypes,
	}.Build()
	File_dizen_common_v1_media_proto = out.File
	file_dizen_common_v1_media_proto_goTypes = nil
	file_dizen_common_v1_media_proto_depIdxs = nil
}
