// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dizen/common/v1/pagination.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cursor-based pagination (03 section 1). The token is opaque to the client: it is sent
// back exactly as it arrived in next_page_token, without being interpreted.
type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of items requested. 0 uses the service default.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Cursor returned by the previous call. Empty requests the first page.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_dizen_common_v1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_common_v1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_dizen_common_v1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Pagination metadata returned by every list response.
type PageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cursor for the next page. Empty means there are no more results.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of items matching the filter. Only populated when it is cheap to
	// compute (03 section 1); otherwise it stays 0.
	TotalSize     int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_dizen_common_v1_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_common_v1_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_dizen_common_v1_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_dizen_common_v1_pagination_proto protoreflect.FileDescriptor

const file_dizen_common_v1_pagination_proto_rawDesc = "" +
	"\n" +
	" dizen/common/v1/pagination.proto\x12\x0fdizen.common.v1\x1a\x1bbuf/validate/validate.proto\"_\n" +
	"\vPageRequest\x12'\n" +
	"\tpage_size\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xc8\x01(\x00R\bpageSize\x12'\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x04R\tpageToken\"U\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSizeB\xd1\x01\n" +
	"\x13com.dizen.common.v1B\x0fPaginationProtoP\x01ZKgithub.com/nicodanke/dizen-v2-backend/pkg/genproto/dizen/common/v1;commonv1\xa2\x02\x03DCX\xaa\x02\x0fDizen.Common.V1\xca\x02\x0fDizen\\Common\\V1\xe2\x02\x1bDizen\\Common\\V1\\GPBMetadata\xea\x02\x11Dizen::Common::V1b\x06proto3"

var (
	file_dizen_common_v1_pagination_proto_rawDescOnce sync.Once
	file_dizen_common_v1_pagination_proto_rawDescData []byte
)

func file_dizen_common_v1_pagination_proto_rawDescGZIP() []byte {
	file_dizen_common_v1_pagination_proto_rawDescOnce.Do(func() {
		file_dizen_common_v1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dizen_common_v1_pagination_proto_rawDesc), len(file_dizen_common_v1_pagination_proto_rawDesc)))
	})
	return file_dizen_common_v1_pagination_proto_rawDescData
}

var file_dizen_common_v1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dizen_common_v1_pagination_proto_goTypes = []any{
	(*PageRequest)(nil),  // 0: dizen.common.v1.PageRequest
	(*PageResponse)(nil), // 1: dizen.common.v1.PageResponse
}
var file_dizen_common_v1_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dizen_common_v1_pagination_proto_init() }
func file_dizen_common_v1_pagination_proto_init() {
	if File_dizen_common_v1_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dizen_common_v1_pagination_proto_rawDesc), len(file_dizen_common_v1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dizen_common_v1_pagination_proto_goTypes,
		DependencyIndexes: file_dizen_common_v1_pagination_proto_depIdxs,
		MessageInfos:      file_dizen_common_v1_pagination_proto_msgTypes,
	}.Build()
	File_dizen_common_v1_pagination_proto = out.File
	file_dizen_common_v1_pagination_proto_goTypes = nil
	file_dizen_common_v1_pagination_proto_depIdxs = nil
}
