// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
select id, aggregate, aggregate_id, routing_key, payload, published_at, attempts, last_error, available_at, created_at from outbox
where published_at is null
  and available_at <= now()
order by id
limit $1
for update skip locked
`

// Claims a batch of events due for publication.
//
// `for update skip locked` is what lets several workers run at once without stepping on
// each other: each takes rows nobody else holds instead of blocking on them.
func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Aggregate,
			&i.AggregateID,
			&i.RoutingKey,
			&i.Payload,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
			&i.AvailableAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingOutboxEvents = `-- name: CountPendingOutboxEvents :one
select count(*) from outbox
where published_at is null
`

// Size of the backlog. Exposed as a metric: a backlog that only grows means the worker is
// not keeping up or the broker is down.
func (q *Queries) CountPendingOutboxEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOutboxEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePublishedOutboxEventsBefore = `-- name: DeletePublishedOutboxEventsBefore :execrows
delete from outbox
where published_at is not null
  and published_at < $1
`

// Prunes already published events. Retention is an operational decision, not a domain one.
func (q *Queries) DeletePublishedOutboxEventsBefore(ctx context.Context, publishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutboxEventsBefore, publishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
insert into outbox (aggregate, aggregate_id, routing_key, payload)
values ($1, $2, $3, $4)
returning id, aggregate, aggregate_id, routing_key, payload, published_at, attempts, last_error, available_at, created_at
`

type InsertOutboxEventParams struct {
	Aggregate   string          `json:"aggregate"`
	AggregateID *string         `json:"aggregate_id"`
	RoutingKey  string          `json:"routing_key"`
	Payload     json.RawMessage `json:"payload"`
}

// Writes an event inside the caller's transaction. It is the only way an event enters the
// outbox: the helper in pkg/outbox always runs it on the transaction in progress.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.Aggregate,
		arg.AggregateID,
		arg.RoutingKey,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Aggregate,
		&i.AggregateID,
		&i.RoutingKey,
		&i.Payload,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
update outbox
set published_at = now()
where id = $1
`

// Marks an event as published once the broker has confirmed it.
func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const rescheduleOutboxEvent = `-- name: RescheduleOutboxEvent :exec
update outbox
set attempts     = attempts + 1,
    last_error   = $2,
    available_at = $3
where id = $1
`

type RescheduleOutboxEventParams struct {
	ID          int64     `json:"id"`
	LastError   *string   `json:"last_error"`
	AvailableAt time.Time `json:"available_at"`
}

// Records a failed attempt and pushes the event forward so the retry backs off.
func (q *Queries) RescheduleOutboxEvent(ctx context.Context, arg RescheduleOutboxEventParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutboxEvent, arg.ID, arg.LastError, arg.AvailableAt)
	return err
}
