type: environment
model: environment
id: env_local
workspaceId: wk_dizen
createdAt: 2026-08-30T14:17:18.027870
updatedAt: 2026-08-30T23:10:24.785445
name: Local
public: true
base: false
parentModel: environment
parentId: null
variables:
- enabled: true
  name: identity_http
  value: http://localhost:8081
  id: TvtzEbVhVj
- enabled: true
  name: identity_grpc
  value: localhost:9091
  id: z9C9kZt4a6
- enabled: true
  name: tours_http
  value: http://localhost:8082
  id: fb0DFjfT43
- enabled: true
  name: tours_grpc
  value: localhost:9092
  id: n2KTkTkFJf
- enabled: true
  name: booking_http
  value: http://localhost:8083
  id: DVvzKHwWDn
- enabled: true
  name: booking_grpc
  value: localhost:9093
  id: m43GWe74Gd
- enabled: true
  name: admin_http
  value: http://localhost:8084
  id: sgqfU4IYUT
- enabled: true
  name: admin_grpc
  value: localhost:9094
  id: E9NPa97WAd
- enabled: true
  name: api_version
  value: 1.0.0
  id: CJpw4dfM4q
- enabled: true
  name: access_token
  value: ''
  id: x0ATAYVVhE
- enabled: true
  name: refresh_token
  value: ''
  id: 6JeZytxxif
color: null
sortPriority: 0.0
