// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/nicodanke/dizen-v2-backend/services/identity/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// ClaimPending provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) ClaimPending(ctx context.Context, limit int32) ([]repository.OutboxEvent, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPending")
	}

	var r0 []repository.OutboxEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]repository.OutboxEvent, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []repository.OutboxEvent); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.OutboxEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutboxRepository_ClaimPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimPending'
type MockOutboxRepository_ClaimPending_Call struct {
	*mock.Call
}

// ClaimPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
func (_e *MockOutboxRepository_Expecter) ClaimPending(ctx any, limit any) *MockOutboxRepository_ClaimPending_Call {
	return &MockOutboxRepository_ClaimPending_Call{Call: _e.mock.On("ClaimPending", ctx, limit)}
}

func (_c *MockOutboxRepository_ClaimPending_Call) Run(run func(ctx context.Context, limit int32)) *MockOutboxRepository_ClaimPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_ClaimPending_Call) Return(outboxEvents []repository.OutboxEvent, err error) *MockOutboxRepository_ClaimPending_Call {
	_c.Call.Return(outboxEvents, err)
	return _c
}

func (_c *MockOutboxRepository_ClaimPending_Call) RunAndReturn(run func(ctx context.Context, limit int32) ([]repository.OutboxEvent, error)) *MockOutboxRepository_ClaimPending_Call {
	_c.Call.Return(run)
	return _c
}

// CountPending provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) CountPending(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountPending")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutboxRepository_CountPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPending'
type MockOutboxRepository_CountPending_Call struct {
	*mock.Call
}

// CountPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOutboxRepository_Expecter) CountPending(ctx any) *MockOutboxRepository_CountPending_Call {
	return &MockOutboxRepository_CountPending_Call{Call: _e.mock.On("CountPending", ctx)}
}

func (_c *MockOutboxRepository_CountPending_Call) Run(run func(ctx context.Context)) *MockOutboxRepository_CountPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_CountPending_Call) Return(n int64, err error) *MockOutboxRepository_CountPending_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOutboxRepository_CountPending_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockOutboxRepository_CountPending_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePublishedBefore provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) DeletePublishedBefore(ctx context.Context, before time.Time) (int64, error) {
	ret := _mock.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeletePublishedBefore")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutboxRepository_DeletePublishedBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePublishedBefore'
type MockOutboxRepository_DeletePublishedBefore_Call struct {
	*mock.Call
}

// DeletePublishedBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockOutboxRepository_Expecter) DeletePublishedBefore(ctx any, before any) *MockOutboxRepository_DeletePublishedBefore_Call {
	return &MockOutboxRepository_DeletePublishedBefore_Call{Call: _e.mock.On("DeletePublishedBefore", ctx, before)}
}

func (_c *MockOutboxRepository_DeletePublishedBefore_Call) Run(run func(ctx context.Context, before time.Time)) *MockOutboxRepository_DeletePublishedBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_DeletePublishedBefore_Call) Return(n int64, err error) *MockOutboxRepository_DeletePublishedBefore_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOutboxRepository_DeletePublishedBefore_Call) RunAndReturn(run func(ctx context.Context, before time.Time) (int64, error)) *MockOutboxRepository_DeletePublishedBefore_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) Insert(ctx context.Context, event repository.NewOutboxEvent) (repository.OutboxEvent, error) {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 repository.OutboxEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.NewOutboxEvent) (repository.OutboxEvent, error)); ok {
		return returnFunc(ctx, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.NewOutboxEvent) repository.OutboxEvent); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Get(0).(repository.OutboxEvent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.NewOutboxEvent) error); ok {
		r1 = returnFunc(ctx, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutboxRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockOutboxRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - event repository.NewOutboxEvent
func (_e *MockOutboxRepository_Expecter) Insert(ctx any, event any) *MockOutboxRepository_Insert_Call {
	return &MockOutboxRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, event)}
}

func (_c *MockOutboxRepository_Insert_Call) Run(run func(ctx context.Context, event repository.NewOutboxEvent)) *MockOutboxRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.NewOutboxEvent
		if args[1] != nil {
			arg1 = args[1].(repository.NewOutboxEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_Insert_Call) Return(outboxEvent repository.OutboxEvent, err error) *MockOutboxRepository_Insert_Call {
	_c.Call.Return(outboxEvent, err)
	return _c
}

func (_c *MockOutboxRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, event repository.NewOutboxEvent) (repository.OutboxEvent, error)) *MockOutboxRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) MarkPublished(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxRepository_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockOutboxRepository_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockOutboxRepository_Expecter) MarkPublished(ctx any, id any) *MockOutboxRepository_MarkPublished_Call {
	return &MockOutboxRepository_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, id)}
}

func (_c *MockOutboxRepository_MarkPublished_Call) Run(run func(ctx context.Context, id int64)) *MockOutboxRepository_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_MarkPublished_Call) Return(err error) *MockOutboxRepository_MarkPublished_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxRepository_MarkPublished_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockOutboxRepository_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Reschedule provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) Reschedule(ctx context.Context, id int64, reason string, retryAt time.Time) error {
	ret := _mock.Called(ctx, id, reason, retryAt)

	if len(ret) == 0 {
		panic("no return value specified for Reschedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, reason, retryAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxRepository_Reschedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reschedule'
type MockOutboxRepository_Reschedule_Call struct {
	*mock.Call
}

// Reschedule is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - reason string
//   - retryAt time.Time
func (_e *MockOutboxRepository_Expecter) Reschedule(ctx any, id any, reason any, retryAt any) *MockOutboxRepository_Reschedule_Call {
	return &MockOutboxRepository_Reschedule_Call{Call: _e.mock.On("Reschedule", ctx, id, reason, retryAt)}
}

func (_c *MockOutboxRepository_Reschedule_Call) Run(run func(ctx context.Context, id int64, reason string, retryAt time.Time)) *MockOutboxRepository_Reschedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_Reschedule_Call) Return(err error) *MockOutboxRepository_Reschedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxRepository_Reschedule_Call) RunAndReturn(run func(ctx context.Context, id int64, reason string, retryAt time.Time) error) *MockOutboxRepository_Reschedule_Call {
	_c.Call.Return(run)
	return _c
}
