// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"
)

type Outbox struct {
	ID          int64           `json:"id"`
	Aggregate   string          `json:"aggregate"`
	AggregateID *string         `json:"aggregate_id"`
	RoutingKey  string          `json:"routing_key"`
	Payload     json.RawMessage `json:"payload"`
	PublishedAt *time.Time      `json:"published_at"`
	Attempts    int32           `json:"attempts"`
	LastError   *string         `json:"last_error"`
	AvailableAt time.Time       `json:"available_at"`
	CreatedAt   time.Time       `json:"created_at"`
}
