// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	// Claims a batch of events due for publication.
	//
	// `for update skip locked` is what lets several workers run at once without stepping on
	// each other: each takes rows nobody else holds instead of blocking on them.
	ClaimPendingOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error)
	// Size of the backlog. Exposed as a metric: a backlog that only grows means the worker is
	// not keeping up or the broker is down.
	CountPendingOutboxEvents(ctx context.Context) (int64, error)
	// Prunes already published events. Retention is an operational decision, not a domain one.
	DeletePublishedOutboxEventsBefore(ctx context.Context, publishedAt *time.Time) (int64, error)
	// Writes an event inside the caller's transaction. It is the only way an event enters the
	// outbox: the helper in pkg/outbox always runs it on the transaction in progress.
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (Outbox, error)
	// Marks an event as published once the broker has confirmed it.
	MarkOutboxEventPublished(ctx context.Context, id int64) error
	// Records a failed attempt and pushes the event forward so the retry backs off.
	RescheduleOutboxEvent(ctx context.Context, arg RescheduleOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
