// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dizen/identity/v1/health.proto

package identityv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthPingRequest) Reset() {
	*x = HealthPingRequest{}
	mi := &file_dizen_identity_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPingRequest) ProtoMessage() {}

func (x *HealthPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_identity_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPingRequest.ProtoReflect.Descriptor instead.
func (*HealthPingRequest) Descriptor() ([]byte, []int) {
	return file_dizen_identity_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthPingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the service answering the call.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Build version (git tag, or "dev").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Commit the binary was built from.
	Commit string `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	// Server time, in UTC.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthPingResponse) Reset() {
	*x = HealthPingResponse{}
	mi := &file_dizen_identity_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPingResponse) ProtoMessage() {}

func (x *HealthPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dizen_identity_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPingResponse.ProtoReflect.Descriptor instead.
func (*HealthPingResponse) Descriptor() ([]byte, []int) {
	return file_dizen_identity_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthPingResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthPingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthPingResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *HealthPingResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_dizen_identity_v1_health_proto protoreflect.FileDescriptor

const file_dizen_identity_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1edizen/identity/v1/health.proto\x12\x11dizen.identity.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11HealthPingRequest\"\x9d\x01\n" +
	"\x12HealthPingResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12;\n" +
	"\vserver_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime2\x87\x01\n" +
	"\rHealthService\x12v\n" +
	"\n" +
	"HealthPing\x12$.dizen.identity.v1.HealthPingRequest\x1a%.dizen.identity.v1.HealthPingResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/identity/healthB\xdb\x01\n" +
	"\x15com.dizen.identity.v1B\vHealthProtoP\x01ZOgithub.com/nicodanke/dizen-v2-backend/pkg/genproto/dizen/identity/v1;identityv1\xa2\x02\x03DIX\xaa\x02\x11Dizen.Identity.V1\xca\x02\x11Dizen\\Identity\\V1\xe2\x02\x1dDizen\\Identity\\V1\\GPBMetadata\xea\x02\x13Dizen::Identity::V1b\x06proto3"

var (
	file_dizen_identity_v1_health_proto_rawDescOnce sync.Once
	file_dizen_identity_v1_health_proto_rawDescData []byte
)

func file_dizen_identity_v1_health_proto_rawDescGZIP() []byte {
	file_dizen_identity_v1_health_proto_rawDescOnce.Do(func() {
		file_dizen_identity_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dizen_identity_v1_health_proto_rawDesc), len(file_dizen_identity_v1_health_proto_rawDesc)))
	})
	return file_dizen_identity_v1_health_proto_rawDescData
}

var file_dizen_identity_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dizen_identity_v1_health_proto_goTypes = []any{
	(*HealthPingRequest)(nil),     // 0: dizen.identity.v1.HealthPingRequest
	(*HealthPingResponse)(nil),    // 1: dizen.identity.v1.HealthPingResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_dizen_identity_v1_health_proto_depIdxs = []int32{
	2, // 0: dizen.identity.v1.HealthPingResponse.server_time:type_name -> google.protobuf.Timestamp
	0, // 1: dizen.identity.v1.HealthService.HealthPing:input_type -> dizen.identity.v1.HealthPingRequest
	1, // 2: dizen.identity.v1.HealthService.HealthPing:output_type -> dizen.identity.v1.HealthPingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dizen_identity_v1_health_proto_init() }
func file_dizen_identity_v1_health_proto_init() {
	if File_dizen_identity_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dizen_identity_v1_health_proto_rawDesc), len(file_dizen_identity_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dizen_identity_v1_health_proto_goTypes,
		DependencyIndexes: file_dizen_identity_v1_health_proto_depIdxs,
		MessageInfos:      file_dizen_identity_v1_health_proto_msgTypes,
	}.Build()
	File_dizen_identity_v1_health_proto = out.File
	file_dizen_identity_v1_health_proto_goTypes = nil
	file_dizen_identity_v1_health_proto_depIdxs = nil
}
