#!/usr/bin/env bash
# Completes the `dizen_api` Dart package after `buf generate`.
#
# protoc-gen-dart only emits the .pb.dart files under lib/src/generated. The rest of the
# package -- pubspec, analysis options, and above all the barrel file that decides what is
# exported -- is assembled here so dizen-v2-mobile consumes it with a single import
# (01 section 3.1).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKG_DIR="$ROOT/gen/dart/dizen_api"
GEN_DIR="$PKG_DIR/lib/src/generated"

if [ ! -d "$GEN_DIR" ]; then
  echo "error: $GEN_DIR is missing; run 'make proto' first" >&2
  exit 1
fi

mkdir -p "$PKG_DIR"

# --- pubspec ---------------------------------------------------------------
cat > "$PKG_DIR/pubspec.yaml" <<'YAML'
# GENERATED by scripts/proto-postgen.sh. Do not edit by hand.
#
# This package is not published to pub.dev: dizen-v2-mobile consumes it as a git
# dependency pinned to an api-vX.Y.Z tag (01 section 3.1).
#
#   dependencies:
#     dizen_api:
#       git:
#         url: https://github.com/nicodanke/dizen-v2-backend.git
#         path: gen/dart/dizen_api
#         ref: api-v0.1.0
name: dizen_api
description: Generated client for the Dizen gRPC contract. Produced from proto/, do not edit.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  fixnum: ^1.1.1
  grpc: ^5.1.0
  protobuf: ^6.0.0
YAML

# --- analysis --------------------------------------------------------------
cat > "$PKG_DIR/analysis_options.yaml" <<'YAML'
# Everything under lib/src/generated is generated code: it is not linted.
analyzer:
  exclude:
    - lib/src/generated/**
YAML

# --- barrel file -----------------------------------------------------------
# Only the messages and stubs under `dizen/**` are exported. The .pb.dart files for
# google/** and buf/validate/** are generated because the code imports them, but they are
# not part of this package's public API.
BARREL="$PKG_DIR/lib/dizen_api.dart"
{
  echo "// GENERATED by scripts/proto-postgen.sh. Do not edit by hand."
  echo "//"
  echo "// Single entry point to the contract: 'import package:dizen_api/dizen_api.dart'."
  echo "library;"
  echo
} > "$BARREL"

find "$GEN_DIR/dizen" \( -name '*.pb.dart' -o -name '*.pbgrpc.dart' -o -name '*.pbenum.dart' \) \
  | sed "s|$GEN_DIR/|src/generated/|" \
  | sort \
  | while IFS= read -r rel; do
      echo "export '$rel';" >> "$BARREL"
    done

# --- documentation ---------------------------------------------------------
cat > "$PKG_DIR/README.md" <<'MD'
# dizen_api

Generated Dart client for the Dizen gRPC contract.

**This package is generated code.** It is produced by `make proto` from `proto/` in the
`dizen-v2-backend` repository, which owns the contract. Do not edit it by hand: any change
is lost on the next generation.

## How it is consumed

From `dizen-v2-mobile`, pinned to a contract tag:

```yaml
dependencies:
  dizen_api:
    git:
      url: https://github.com/nicodanke/dizen-v2-backend.git
      path: gen/dart/dizen_api
      ref: api-v0.1.0
```

The `api-vX.Y.Z` tag is created by the backend CI whenever the contract changes, and it
opens the bump pull request in `dizen-v2-mobile` (01 sections 3.1 and 3.2).
MD

echo "    gen/dart/dizen_api ($(find "$GEN_DIR/dizen" -name '*.dart' | wc -l | tr -d ' ') files exported)"
